### ISSUE TITLE
Child collections, .Include available? 

### ISSUE THREAD

**Issue by mjuen** [AutoMapper/AutoMapper.Collection.EFCore#11]
Is there something similar to `.Include()` in EFCore? 

It has been added to AutoMapper.EntityFramework a while ago.
https://github.com/AutoMapper/AutoMapper.Collection/pull/83

**Comment by Tasteful** [comment]
@mjuen No, it does not exists but you are welcome to create a PR.

The related PR/Issue in AM.Collection for EF is closed without any action.

**Comment by mjuen** [comment]
Oh sorry, totally missed that it wasn't merged. I might consider creating a PR, but it will probably take some time.

Thanks in the meantime!
