### ISSUE TITLE
0.3 Release

### ISSUE THREAD

**Issue by dchristensen** [AutoMapper/AutoMapper.Collection.EFCore#19]
It looks like, based on the [commits in master](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/commit/96438d70ce06c09a60012a8f7a7d136ec938b0ce) that @TylerCarlson1 had intended to do a 0.3 release containing the async changes to the `IPersistence`  interface, however those changes were never released to Nuget.  Is there any chance we could get another Nuget release?

**Comment by ntziolis** [comment]
@TylerCarlson1 Any update on this. Are you looking for additional maintainers?
