### ISSUE TITLE
Problems with updating to v1.0 

### ISSUE THREAD

**Issue by iashaik** [AutoMapper/AutoMapper.Collection.EFCore#25]
Upgrading to version 1.0 requires a dependency of a pre-release version of AutoMapper.Collection (>= 6.0.0-ci-00095), 

I am forced to upgrade to v 1.0 because some other update (AutoMapper?) causes issues with Persist.

**Comment by TylerCarlson1** [comment]
@iashaik The reference is updated back to 5.0.0.

**Comment by iashaik** [comment]
this is closed?
