### ISSUE TITLE
Blazor Client Compatability

### ISSUE THREAD

**Issue by Newmski** [AutoMapper/AutoMapper.Collection.EFCore#31]
Hi,

I looking into the feasibility of using Blazor Client for as the front end for an existing project and am running into the following error:

```
Unhandled exception. Mono.Linker.MarkException: Error processing method: 'AutoMapper.PropertyMap AutoMapper.Mappers.ExpressionMapper/MappingVisitor::PropertyMap(System.Linq.Expressions.MemberExpression)' in assembly: 'AutoMapper.Extensions.ExpressionMapping.dll'

ILLink failed with exited code -532462766.
```

I am trying to replicate the issue in a stand alone application but as soon as I add the AutoMapper.Collection.EntityFrameworkCore package I receive a similar error which says:

```
Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.IDisposable Microsoft.Extensions.Logging.Logger::BeginScope(TState)' in assembly: 'Microsoft.Extensions.Logging.dll'

ILLink failed with exited code -532462766.
```

Steps to reproduce the behaviour:

1 - Create a new Blazor WebAssembly App
2 - Add the AutoMapper nuget package
2 - Add the AutoMapper.Collection.EntityFrameworkCore package
3 - Build the solution

**Comment by Tasteful** [comment]
Hi,

Not sure if this is caused by this library at all, the error messages is pointing to `AutoMapper.Extensions.ExpressionMapping` and `Microsoft.Extensions.Logging` library.

If you remove the `AutoMapper.Collection.EntityFrameworkCore` and add these above libraries directly (remember to make reference to them). Will the linker then work?

**Comment by Newmski** [comment]
Thanks for your quick reply.

I can confirm that building an empty Blazor WebAssembly App with `AutoMapper.Extensions.ExpressionMapping` and `Microsoft.Extensions.Logging` added via NuGet Package Manager does not cause the error.

An empty app with `AutoMapper.Collection.EntityFrameworkCore` still produces the error.

Looking through the packages it appears that `AutoMapper.Collection.EntityFrameworkCore` is using `AutoMapper.Extensions.ExpressionMapping (2.0.0)`, the version I see when a download it directly from NuGet is 3.0.5.  Similarly `Microsoft.Extensions.Logging (2.1.1)` is 3.1.1 when added via NuGet.

**Comment by Tasteful** [comment]
Please, can you come back with an example that is complete and can be executed directly that will create the issue? I tried with your steps above but was not able to get this error so I guess I'm doing something wrong or some steps that are missing.

**Comment by Newmski** [comment]
I have created an example on [https://github.com/Newmski/BlazorDemoApp](url)

It is an empty Blazor WebAssembly solution with the AutoMapper.Collection.EntityFrameworkCore NugGet package installed.

When I build the solution I get the following:

![Errors](https://user-images.githubusercontent.com/16361231/73177494-16201800-4107-11ea-9b78-ca6e56891647.jpg)

If I remove the NuGet package the error goes away.

**Comment by Tasteful** [comment]
When you only adding the `AutoMapper.Collection.EntityFrameworkCore` package it will include a lot of dependencies, they are not always the latest version and in this case the `Microsoft.EntityFrameworkCore` is version `2.1.1`. If you upgrade this package to `3.1.1` in your project the build is working fine.

**Comment by Newmski** [comment]
I was reluctant to add another dependency on `Microsoft.EntityFrameworkCore` because the `AutoMapper.Collection.EntityFrameworkCore` specifically targets `2.1.1` [here ](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/blob/master/src/AutoMapper.Collection.EntityFrameworkCore/AutoMapper.Collection.EntityFrameworkCore.csproj) and I wasn't sure if it would cause unexpected behaviour when moving from v2 to v3.

In the long term will this project be updated to use the more recent v3 `Microsoft.EntityFrameworkCore` dependency?

**Comment by Tasteful** [comment]
The library is compatible with EFCore 3.0.1 (that is used during test) so I think it will be compatible with newer versions also. You only have to update your dependency to use the newer version, new version of this package is not needed.

**Comment by Newmski** [comment]
Ok will do, thanks for your help.
