### ISSUE TITLE
Update for AutoMapper.Collections v6

### ISSUE THREAD

**Issue by Baune8D** [AutoMapper/AutoMapper.Collection.EFCore#35]
AutoMapper.Collections has been updated to support AutoMapper v10. Can i use this package, or do i need to wait for an update to bump references to AutoMapper.Collections to v6?

**Comment by Tasteful** [comment]
I think it should work, the logic in this package is about efcore and as far as I can remember the public api of AM.Collection is not changed.

Please, try it out :)
