### ISSUE TITLE
Method not found: 'IMapper.Map(Object, Type, Type)'

### ISSUE THREAD

**Issue by Sina-Soltani** [AutoMapper/AutoMapper.Collection.EFCore#36]
Hi,
I did exactly like what the document says but I got this exception:

```
System.MissingMethodException: Method not found: 'System.Object AutoMapper.IMapper.Map(System.Object, System.Type, System.Type)'.
   at AutoMapper.EntityFrameworkCore.Persistence`1.GetEquivalenceExpression(Type type, Object from)
   at AutoMapper.EntityFrameworkCore.Persistence`1.InsertOrUpdateAsync(Type type, Object from, CancellationToken cancellationToken)
   at WebApplication1.Controllers.HomeController.Update(CategoryViewModel viewModel)
```

Startup.cs:
```c#
services.AddDbContext<DataContext>(builder => builder.UseSqlServer("Connection String"));

services.AddAutoMapper((provider, config) =>
{
   config.AddCollectionMappers();
   config.UseEntityFrameworkCoreModel<DataContext>(provider);
}, typeof(DataContext).Assembly);
```

Usage:
```c#
public class CategoryService
{
   public CategoryService(IMapper mapper) { } .......

   public Task Save(CategoryViewModel viewModel)
   {
      return _db.Categories.Persist(_mapper).InsertOrUpdateAsync(viewModel);
   }
}
```

Packages:
* AutoMapper 10.0.0
* AutoMapper.Collection 7.0.0
* AutoMapper.Collection.EntityFrameworkCore 1.0.1
* AutoMapper.Extensions.ExpressionMapping 4.0.0
* AutoMapper.Extensions.Microsoft.DependencyInjection 8.0.1
* Microsoft.EntityFrameworkCore 3.1.6

**Comment by iashaik** [comment]
Same boat. 

``System.MissingMethodException: Method not found: 'System.Object AutoMapper.IMapper.Map(System.Object, System.Type, System.Type)'.
    at AutoMapper.EntityFrameworkCore.Persistence`1.GetEquivalenceExpression(Type type, Object from)
   at AutoMapper.EntityFrameworkCore.Persistence`1.InsertOrUpdate(Type type, Object from)
   at AutoMapper.EntityFrameworkCore.Persistence`1.InsertOrUpdate[TFrom](TFrom from)
``

And I came to report this issue.

**Comment by iashaik** [comment]
@jbogard @TylerCarlson1 It got broken somewhere between AutoMapper 10.0 and AutoMapper.Collection 7.0, because it was working with AutoMapper 9.0 and AutoMapper.Collection 6.0

**Comment by Sina-Soltani** [comment]
I think so.
This exception normally happens when a nuget package calls another project's method which doesn't exist anymore in the newer version.

**Comment by Tasteful** [comment]
The AM.Collection.EFCore is not recompiled for AM 10 so the binary breaking change in AM will make it to break.

**Comment by risogolo** [comment]
And any plans to fix this?

**Comment by jbogard** [comment]
PR is welcome. I don't use this library myself.
