### ISSUE TITLE
prefer default not default(T)

### ISSUE THREAD

**Issue by DickBaker** [AutoMapper/AutoMapper.Collection.EFCore#37]
compiling the code throws up a suggestion IDE0034 (in 6 places) where these 3 URLs relate
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default#default-literal
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#csharp_prefer_simple_default_expression
https://docs.microsoft.com/en-us/visualstudio/ide/common-quick-actions?view=vs-2019#remove-type-from-default-value-expression

AFAIK this relates to C# 7.1+ and Visual Studio 2017 version 15.3 and later, so can now be considered a stable mature change
 - do we really need to provide backward-facing code to prior versions ?

Evidently Eric St-Georges thought so in 26/03/2019 15:52:18 with Commit 0a4a3e42 but I challenge that now
 - please revert and accept the IDE0034 recommendations

BTW whilst you're at it could you pretty please change "EntityFramworkCoreTestsBase.cs" to "EntityFrameworkCoreTestsBase.cs" (external file-name and internal class-name) as this grates every time I see it. TIA

**Comment by TylerCarlson1** [comment]
Pull Requests are welcome if you want to have it changed.

**Comment by DickBaker** [comment]
great & thanks for accepting my PR and integrating as 5dc1452 so onwards and upwards!
