### ISSUE TITLE
Problem with Automapper 10

### ISSUE THREAD

**Issue by pampua84** [AutoMapper/AutoMapper.Collection.EFCore#45]
Hi, today i tried to install this package on my infrastructure project where are installed:

Automapper 10.0.0
IdentityServer4.EntityFramework.Storage 4.0.4

but when i try to use  use _mapper.Map(src, dest) i obtain alway an exception like this:

Method not found: 'System.Object AutoMapper.IMapper.Map(System.Object, System.Type, System.Type)

if i remove this package it works fine. 
There is incompatibility with automapper 10.0.0?

**Comment by Tasteful** [comment]
The AM.Collection.EFCore is not recompiled for AM 10 so the binary breaking change in AM will make it to break.

Duplicate #36

**Comment by risogolo** [comment]
And any plans to fix this?
