### ISSUE TITLE
Weird Error using Persistance

### ISSUE THREAD

**Issue by iashaik** [AutoMapper/AutoMapper.Collection.EFCore#53]
I have trouble sometimes using Persist on certain models and I get the following error. 

```
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.
Mapping types:
Object -> Object
System.Object -> System.Object
   at lambda_method30(Closure , Object , Object , ResolutionContext )
```

It originates in [Persistance.cs](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/blob/master/src/AutoMapper.Collection.EntityFrameworkCore/Persistence.cs) at 

`  private Expression<Func<TTo, bool>> GetEquivalenceExpression(Type type, object from) => _mapper.Map(from, type, typeof(Expression<Func<TTo, bool>>)) as Expression<Func<TTo, bool>>;`

Mapping at everything is fine because 

This Works 

```
  NameEntity entity = _mapper.Map<NameEntity>(new NameModel() { Name = "Adding without Persist" });
  _context.Set<NameEntity>().Add(entity);
  await _context.SaveChangesAsync();
```

This throws. 

```
 await _context
          .Set<NameEntity>()
          .Persist(_mapper)
          .InsertOrUpdateAsync(new NameModel() { Name = "Adding with Persist" });
```

I am able to replicate the problem in isolation, see[ this repository for details.](https://github.com/iashaik/EntityFramework.AutoMapper.WorkerService )

**Comment by ByZhouhang** [comment]
I also encountered this problem  in   net 6，did  you  fix the problem ?

**Comment by Tasteful** [comment]
When using map without persist the entity is mapped and later added to context. 

When the persist is used the source property mapped to the id property on target to see if an add or update should be executed. In this case the `NameModel` missing the id property and persist mapping cant be done.
