### ISSUE TITLE
System.MissingFieldException: Field not found: 'AutoMapper.Internal.TypePair.DestinationType' when also mapping the entities manually

### ISSUE THREAD

**Issue by fuji97** [AutoMapper/AutoMapper.Collection.EFCore#66]
If `.UseEntityFrameworkCoreModel()` is used together with other manual mappings, the application crash with the following error:
`Unhandled exception. System.MissingFieldException: Field not found: 'AutoMapper.Internal.TypePair.DestinationType'.`

Example of configuration that crashes the application:
```C#
var serviceProvider = new ServiceCollection()
    .AddDbContext<FoobarDbContext>()
    .AddAutoMapper((serviceProvider, automapper) =>
    {
        automapper.AddCollectionMappers();
        automapper.UseEntityFrameworkCoreModel<FoobarDbContext>(serviceProvider);
        automapper.CreateMap<Foo, FooDto>().ReverseMap();
        automapper.CreateMap<Bar, BarDto>().ReverseMap();
    }, typeof(FoobarDbContext).Assembly)
    .BuildServiceProvider();
```
The full minimal project that causes the crash can be found [here](https://github.com/fuji97/AutoMapperEFCoreBug)

**Comment by lbargaoanu** [comment]
Upgrade!
