### ISSUE TITLE
ChangeTracker gets navigationmembers as Added when using InsertOrUpdate()

### ISSUE THREAD

**Issue by JakobWl** [AutoMapper/AutoMapper.Collection.EFCore#69]
I have been struggling a lot with this lately and maybe it is intended or I am using it wrong.

Whenever I use InsertOrUpdate with a dto that has navigation properties that didnt change before send back to the backend,
the ef changetracker marks it as Added wich in return results in a duplicate key database exception.

In case there is existing data in the database. For example a Bar with Id 1 and a Foo with Id 1 and BarId 1 .

```
public class Foo
    {
        public int Id { get; set; }
        public int BarId { get; set; }
        public Bar bar { get; set; }
    }

public class Bar
    {
        public int Id { get; set; }
    }

public class BarDto
    {
        public int Id { get; set; }
    }


public class FooDto
    {
        public int Id { get; set; }
        public int BarId { get; set; }
        public BarDto bar { get; set; }
    }
```

And I try to add a new FooDto with Id 2 and BarId 1 and the BarDto with Id 1.

```
await _context.Foos.Persist(_mapper).InsertOrUpdateAsync(fooDto);
```

The ChangeTracker of EntityFramework marks Bar{Id:1} as Added???
It obviously doesnt try to attach it in any way or check if it already exists.

**Comment by oakular** [comment]
I cannot see you mapper configuration, but this looks very similar to this issue I am having #70.

@JakobWl are you getting this error on `SaveChanges`?

```
The instance of entity type 'Bar' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.
```

**Comment by JakobWl** [comment]
Yes your issue is defentely what i mean but i came to accept that automapper works this way. I realised that just ignoring all virtual navigation properties except collections is for me at least a working solution. It results in the expected way automapper.collection in my opinion showld work with entity framework.

I made this extension to solve all my problems. Also with having many to many relationships with custom mapping tables although this is not a concern of this issue i will also post it here.

```
public static class MapperExtenstions
	{
		public static void ManyToManyMap<TSource, TMappingTable>(
			this IRuntimeMapper mapper, 
			ICollection<TSource> source, 
			ICollection<TMappingTable> destination, 
			Func<TSource, TMappingTable, bool> search, 
			Func<TSource, IRuntimeMapper, TMappingTable> createDest) where TSource : IDto
		{
			if (source == null || source.Any(x => x == null))
			{
				return;
			}

			destination
				.Where(dest => !source.Any(x => search(x, dest))).ToList()
				.ForEach(deleted => destination.Remove(deleted));

			foreach (var item in source.Where(x => !destination.Any(y => search(x, y))))
			{
				destination.Add(createDest(item, mapper));
			}
		}

        public static IMappingExpression<TSource, TDestination>
               IgnoreAllVirtualExceptCollections<TSource, TDestination>(
                   this IMappingExpression<TSource, TDestination> expression)
        {
            var desType = typeof(TDestination);
            foreach (var property in desType.GetProperties()
				.Where(p => p.GetGetMethod().IsVirtual && 
				!p.GetGetMethod().IsFinal && 
				!typeof(IEnumerable).IsAssignableFrom(p.PropertyType)))
            {
                expression.ForMember(property.Name, opt => opt.Ignore());
            }

            return expression;
        }
    }
```

Hope it helps someone

**Comment by oakular** [comment]
@JakobWl thank you for sharing your extension methods. This is clearly an underlying limitation of AutoMapper then.

I have decided to enforce manual mapping from DTO -> Entity in our converters, as we really would benefit from the rich relationship definitions in our business layers.
