### ISSUE TITLE
Update Documentation and Error Message

### ISSUE THREAD

**Issue by gregoryagu** [AutoMapper/AutoMapper.Collection.EFCore#7]
I just installed and ran the 0.1.0.  It threw an error when I tried to run it as per the ReadMe.  The README.md file should be updated to reflect name change:

Current ReadMe:

```
Mapper.Initialize(cfg =>
{
    cfg.AddCollectionMappers();
    cfg.SetGeneratePropertyMaps<GenerateEntityFrameworkCorePrimaryKeyPropertyMaps<DB>>();
    // Configuration code
});
```

Should read:

```
Mapper.Initialize(cfg =>
{
    cfg.AddCollectionMappers();
    cfg.UseEntityFrameworkCoreModel<GenerateEntityFrameworkCorePrimaryKeyPropertyMaps<DB>>();
    // Configuration code
});
```

The current error message thrown when using cfg.SetGeneratePropertyMaps:

`InvalidOperationException: Use AddEntityFrameworkCoreKeys instead of using SetGeneratePropertyMaps.`

Should be updated to:

`InvalidOperationException: Use UseEntityFrameworkCoreModel instead of using SetGeneratePropertyMaps.
`

**Comment by andrebugs2** [comment]
Sorry for hijacking this, but I cannot get this working at all using GenerateEntityFrameworkCorePrimaryKeyPropertyMaps. I have made a small demo demonstrating my problem here:

https://github.com/andrebugs2/AutoMapperCollectionProblem/tree/master/AutomapperTest/AutomapperTest

As you can see in Startup.cs I use the following:

```
services.AddAutoMapper((serviceProvider, cfg) =>
{
                cfg.AddCollectionMappers();
                cfg.UseEntityFrameworkCoreModel<GenerateEntityFrameworkCorePrimaryKeyPropertyMaps<MyDbContext>>(services);
});
```

I get the below error. I have usings for AutoMapper, AutoMapper.EntityFrameworkCore and AutoMapper.EquivalencyExpression. What am I missing? MyDbContext extends from DbContext.

'AutoMapper.EntityFrameworkCore.GenerateEntityFrameworkCorePrimaryKeyPropertyMaps<AutomapperTest.MyDbContext>' cannot be used as type parameter 'TContext' in the generic type or method 'MapperConfigurationExpressionExtensions.UseEntityFrameworkCoreModel<TContext>(IMapperConfigurationExpression, IServiceCollection)'. There is no implicit reference conversion from 'AutoMapper.EntityFrameworkCore.GenerateEntityFrameworkCorePrimaryKeyPropertyMaps<AutomapperTest.MyDbContext>' to 'Microsoft.EntityFrameworkCore.DbContext'.	AutomapperTest	C:\Users\dahlqand\AutoMapperCollectionProblem\AutomapperTest\AutomapperTest\Startup.cs	27	Active

**Comment by jbogard** [comment]
New issue?
