### ISSUE TITLE
include navigation properties for persist

### ISSUE THREAD

**Issue by hiaselhans** [AutoMapper/AutoMapper.Collection.EFCore#76]
I have the following example:

``` c#
class BlogPost
{
    public long Id { get; set; }
}

class BlogComment
{
    public long Id { get; set; }
    public long BlogPostId { get; set; }
    public virtual List<BlogPost> Posts { get; set; }
}
```

with the same structure for the dto's
I would like to update the BlogComments with automapper collections:

``` c#
var dbRecord = PlogPosts.Persist(mapper).InsertOrUpdate(BlogPostDTO);
```

Everything works fine but when i delete Comment objects from BlogPostDTO, they are not removed from the database.
During debugging, i found that dbRecord has the relevant comment deleted but the collection isn't included in the database call and thus not tracked.

like with conventional mapping:

``` c#
// this works
dbRecord = await BlogPosts.Where(x=>x.Id ==id).Include(x=>x.Comments).FirstAsync()
mapper.Map(RecordDTO, dbRecord)

// this does not remove the items from the database
dbRecord = await BlogPosts.Where(x=>x.Id ==id).FirstAsync()
mapper.Map(RecordDTO, dbRecord)
```

Is there a way to make this working generically?

**Comment by hiaselhans** [comment]
@lbargaoanu i see this was closed.
Is there a solution to this or is it just "not planned"?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
