### ISSUE TITLE
UseEntityFrameworkCoreModel + AppilcationInsights SDK causes IOptionsMonitor to stop updating with config changes

### ISSUE THREAD

**Issue by mike-jarosch-aw** [AutoMapper/AutoMapper.Collection.EFCore#77]
When using the Application Insights SDK to add telemetry to your application, calling UseEntityFrameworkCoreModel will cause any IOptionsMonitors to stop updating with config changes. 

I have attached a sample project that recreates it. It does require an Azure Application Insights and Azure App Configuration for the best visibility of the bug.

**Setup**

1. Create test Azure resources (App Insights and App Configuration) and note the connection strings.
2. Update the appsettings.Development.json with the connection strings.
3. In App Configuration, add a "Test:Name" variable with any value. Add a "Test:Sentinel" value with a Label of "Test" and a value of 1.

![image](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/assets/42348459/41b8b453-2b6e-490a-abed-74e112f38c2b)

**Steps**

1. Run the application in visual studio.
2. Execute the "test/sayHello" endpoint and see it displays the name in App Configuration
3. Execute the "test/showConfig" endpoint and see it contains the Name and Sentinel value from App Configuration
4. Execute the "facts/getFact" endpoint and enjoy the fun dog fact. The remote call is not necessary, I just wanted the endpoint to do something. The important piece is that it will receive an IMapper from the DI container.
5. Update the Name and Sentinel values in App Configuration.
6. Execute the "test/sayHello" endpoint a few time and see it still displays the previous Name.  
7. Execute the "test/showConfig" endpoint and see it contains the updated Name and Sentinel values.

**Notes**

- You can re-create the issue without App Configuration, but you will not see the "test/showConfig" update with new values. I believe this is because the settings file monitoring uses the same functionality that is used to update OptionsMonitors

[ConfigurationRefresh.zip](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/files/13527900/ConfigurationRefresh.zip)

**Comment by mjarosch** [comment]
Was this fixed or just closed?
