### ISSUE TITLE
Mapping child collection to an existing object?

### ISSUE THREAD

**Issue by plettb** [AutoMapper/AutoMapper.Collection.EFCore#80]
I have a database class and a DTO that both have a child collection (e.g. Member/MemberDto with a collection of Email/EmailDto).  When I map an incoming DTO to a new object, everything seems to work perfectly.  However, when I map an incoming DTO to an existing object, the child collection does not get mapped.  What am I doing wrong?

I have the following in my AutoMapper configuration:
```
cfg.AddCollectionMappers();
cfg.AddProfile<DtoMapperProfile>();
cfg.UseEntityFrameworkCoreModel<MyDbContext>(serviceProvider);
```

Whereas I can accomplish the child collection mapping with an "AfterMap", I have quite a number of these scenarios and, since I assume I'm not the first to encounter this (in fact I assume it's a fairly common problem), I assume this is already solved somewhere.  Help?

I don't know if it matters, but I'm using a TPT inheritance hierarchy (i.e. Member inherits Contact, and it's Contact that actually has the child collection of Email).

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
