### ISSUE TITLE
Interface mappings

### ISSUE THREAD

**Issue by azzageee** [AutoMapper/AutoMapper.Collection.EFCore#81]
I am running into an issue where the InsertOrUpdate is unable to recognise a mapping when an interface type is passed as the object to the command.

E.g. Let's assume that we have a mapping configuration for IThing -> Thing.

`x.CreateMap<IThing, Thing>();`

And we have an object ThingDto that implements the IThing interface.

If we were to use a basic mapper operation, we would get a successful mapping:

```
IThing interfaceObject = new ThingDto { ID = 1, Title = "Test" };

var validEntity = mapper.Map<Thing>(interfaceObject);
```

However, when passing an interface type into the `.InsertOrUpdate()` method, this would give an error relating to invalid mapping configuration.

`db.Things.Persist(mapper).InsertOrUpdate(interfaceObject);`

Why is it unable to register the valid mapping that exists for the Interface to concrete entity type?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
